### ISSUE TITLE
Binding fails with "SonarQube request failed: Failed to write credentials"

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1209]
### Description

See the following two community forum threads: [here](https://community.sonarsource.com/t/error-binding-vs-2017-solution-failed-to-write-credentials/3500) and [here](https://community.sonarsource.com/t/not-able-to-connect-to-sonarqube-7-7-from-visual-studio-2017-using-sonarlint-4-10/11468).

### Expected behavior

Credentials should be saved successfully and the binding process completed.

### Actual behavior

The binding process failed.

### Known workarounds

None

### Related information

* SonarLint for VS Version: 4.6.
* Visual Studio Version: ? 
* Languages in your solution; C#

### Notes
We've been unable to repro the issue locally.

The `Failed to write credentials` error message is thrown by the `Microsoft.Alm.Authentication` component as the result of a failed Win32 API call. The API is throwing `Win32Exception` which should have the HRESULT error code. Unfortunately, we aren't logging that part so we're losing the Windows error code.

In the absence of a repro, we could amend the logging to capture the Windows error code to give us a better idea of what the underlying issue might be.

**Comment by RogerW-VZC** [comment]
Same error, VS2019  16.4.6.

I get one additional line before the "Failed to write credentials" error.
"Ruleset binding: all projects need to be updated reference the generated ruleset."

Every time the binding tries to run, an additional ruleset file is added to every project.

I have just deleted the .sonarlint and .sonarqube folders, etc  as recommended https://groups.google.com/forum/#!topic/sonarlint/_hgsvV6WHEU because I needed to switch from a localhost sonarqube to our corporate one.
