### ISSUE TITLE
[Connected mode] Improve token-based authentication UX

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#1247]
### Description

The UX for token-based authentication is confusing and insecure. In the connection dialogue, the user to has to enter the token in the "User name/token" field and leave the password field blank:

![image](https://user-images.githubusercontent.com/10757559/75369791-0178a080-58bc-11ea-8167-bc6e66345b0c.png)

There should be a separate UX for tokens, and the token should never be displayed in clear text.

TODO:
- [ ] agree the new UI with UX
- [ ] code and test (WPF, rework the UI validation logic, update the tests)
- [ ] update documentation/screenshots e.g. the [wiki page](https://github.com/SonarSource/sonarlint-visualstudio/wiki/Connected-Mode)

#### Previous related bugs:
* #1081: Connection dialogue displays the user name/token for the previous connection
* #768: SonarQube token is visible in Credential Manager

**Comment by JohnRambo1993** [comment]
May I add a suggestion: 
It would be cool if you could reuse a previous credential to the same *SonarQube* instance (like a ComboBox for already provided server URLs?). 

When you bind a new solution, you have to provide a URL and a *SonarQube* token. Since the token is only visible once on the *SonarQube* security-page when you generate it, you either have to store the token elsewhere (like *KeePass* or other software) for future uses or generate a new token each time you want to bind a new *Visual Studio* soution to a *SonarQube* project. But if you generate a new token and use it for the new solution, only the new token is getting used for that URL. The old tokens get unused and you therefore should revoke them.

**Comment by duncanp-sonar** [comment]
@JohnRambo1993 that's a good suggestion, and I think it's what we do in the other flavours of SonarLint.

**Comment by vnaskos-sonar** [comment]
To be fixed on https://sonarsource.atlassian.net/browse/MMF-3869
