### ISSUE TITLE
Use Directory.Build.targets to enable connected mode in VS2017

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonarlint-visualstudio#133]
SonarLint connected mode currently modifies all project inside a solution. This is not ideal as the git changeset becomes quite large just because of enabling the connected mode.

VS2017, which uses msbuild vNext, allows using Directory.Build.targets (see https://github.com/Microsoft/msbuild/issues/222), which is a single target file copied next to the .sln file. (This could also be used in the Scanner for MsBuild instead of the ImportsBefore file, but there the gain is not significant. Also mentioned in [MMF-484](https://jira.sonarsource.com/browse/MMF-484).) This file is being picked up during the build, so we could inject analyzers and rulesets through this target file.

We need to check if this works for the on the fly analysis too. (Chances are that it doesn't, but if it does, then that improves the connected mode greatly)

**Comment by JunielKatarn** [comment]
Semi-related question. Is there a way to have the build process (i.e. `dotnet restore`, `dotnet msbuild`) pick up `Directory.Build.targets`? It currently seems ignored.

**Comment by Evangelink** [comment]
Hi @JunielKatarn! Sorry, we haven't had yet the opportunity to have a look at this.

**Comment by japj** [comment]
Hi, any update on the state/roadmap of this?

**Comment by valhristov** [comment]
Hi @japj, we still cannot provide a concrete date for the implementation of this ticket. It seems, however, that it affects multiple end user features (parallel builds on the same machine and enabling connected mode without touching the project files to say the least), could you specify which of those do you need?

**Comment by japj** [comment]
It is about enabling connected mode without touching the project files (note I came across this sonarlint-visualstudio issue while I was looking into some other MSBuild related items).

We have a large number of solution and projects in our product and want to use connected mode. There is a fair bit of customization in our MSBuild environment, thus the "cleaner" sonarlint-visualstudio can integrate (e.g. without modifying existing projects and solutions), the better it would be us.

**Comment by duncanp-sonar** [comment]
We'd done some investigation and concluded that it's unlikely we use _Directory.Build.props_ so I'm closing this ticket. It's likely that users will increasingly create their own _Directory.Build.props_ so we'd be back in the position of having to locate and update a user-created file (and locating the correct _Directory.Build.props_ would be more complicated as we'd have to duplicate the search logic).

Reducing the amount of configuration required is still a goal and is being tracked by [MMF-1048](https://jira.sonarsource.com/browse/MMF-1048).

**Comment by EvanMulawski** [comment]
I am interested in this option as well. We have a legacy solution with over 200 projects, so the per-project configuration and rulesets are burdensome (not to mention updating causes the extension and VS to hang for several minutes). I ended up creating a Directory.Build.props file referencing the generated solution-level ruleset and will maintain it manually until this is officially supported.

Would it be acceptable to have the extension automatically create an MSBuild file so all the user has to do is import it in an existing Directory.Build.props file?

**Comment by duncanp-sonar** [comment]
@EvanMulawski 
> I ended up creating a Directory.Build.props file referencing the generated solution-level ruleset and will maintain it manually until this is officially supported.

That's exactly what we've done for the SLVS solution itself. However, I'm not clear what it is you need to maintain. If your `Directory.Build.props` file references the generated ruleset and your projects pick up the `Directory.Build.props` file then SonarLint will be happy and won't try to make changes to projects.

> Would it be acceptable to have the extension automatically create an MSBuild file so all the user has to do is import it in an existing Directory.Build.props file?
What would be in the MSBuild file - just the property setting for `CodeAnalysisRuleSet` pointing to the generated ruleset?

**Comment by EvanMulawski** [comment]
@duncanp-sonar 

Thanks for the response.

> If your Directory.Build.props file references the generated ruleset and your projects pick up the Directory.Build.props file then SonarLint will be happy and won't try to make changes to projects.

This is not what I am experiencing. If I attempt to update the ruleset, a project-level ruleset is generated and added to each project.

The following banner also appears in the Error List window when opening the solution:

```
One or more rule sets are out of date or not linked to the SonarQube quality profile rule set. See output window (SonarLint) for affected projects. [Update]
```

Output window:

```
...
Checking for unbound projects.
192 unbound projects were found ...
...
```

**Repository Structure**

```
.sonarlint\org_project-name.ruleset
lib\Solution.slconfig
Directory.Build.props
Solution.sln
```

**Directory.Build.props**

```xml
<Project>
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory).sonarlint\org_project-name.ruleset</CodeAnalysisRuleSet>
    </PropertyGroup>
</Project>
```

> What would be in the MSBuild file - just the property setting for CodeAnalysisRuleSet pointing to the generated ruleset?

Yes (same content as above). The user could then import it into an existing Directory.Build.props file (or a new one).

**Comment by duncanp-sonar** [comment]
@EvanMulawski,

(A) SLVS not honouring the Directory.Build.props file
That issue should have been fixed (#859 released in SLVS [v4.9](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/4.9.0.4314)). Which versions of VS and SLVS are you using?

(B) Contents of the MSBuild file
I'm not sure that having an MSBuild file that you have to manually import in the `Directory.Build.props` file is any simpler than just manually setting the `CodeAnalysisRuleset` property in the `Directory.Build.props` file. Also, an MSBuild project with only that content only work for single-language solutions (i.e. projects are either all C# or all VB.NET).

Both approaches suffer from the major drawback that they require manual editing. The binding process should set up the projects so that they are correctly configured without further manual intervention by the end user. The currently project-level binding process is "noisy" in so far as it makes a lot of changes to every project, but it is at least automatic and handles the possible scenarios correctly (e.g. projects that don't have a ruleset specified, projects that already have a ruleset, mixed-language solutions).

**Comment by EvanMulawski** [comment]
(A) `4.15.0.14069` - Do you want to continue discussion in #859?

(B) True, but if it was made an option at bind time, the user wouldn't have to undo the project-level changes if they wanted one ruleset for the entire solution. And automatically generating/updating an MSBuild project file would result in one less step for the user - they reference it once and it doesn't matter if it changes (e.g. additions/changes due to extension updates). I guess it comes down to the number of people wanting solution-level analysis using a single language versus other combinations.

**Comment by duncanp-sonar** [comment]
(A) Please create a new issue, including if possible a copy of your `Directory.Build.props` file and the version of VS you are using.

(B) I've been through the backlog today and tagged quite a few tickets as [relating to binding](https://github.com/SonarSource/sonarlint-visualstudio/labels/Sub-area%3A%20Binding). Some are bugs, some are about simplifying the process. It's likely that we'll re-work the whole binding process this calendar year.
