### ISSUE TITLE
Support SQ file exclusions

### ISSUE THREAD

**Issue by fmallet** [SonarSource/sonarlint-visualstudio#194]
Project exclusion is supported in SL, but with the Scanner for MsBuild, it's possible to exclude files too. In order to report exactly the same issues, we would need to support that in SonarLint too.
One way of doing this would be to pass the excluded file list to SonarAnalyzers as additional files. But at the moment we shouldn't invest more into additional files as they are changing as Roslyn matures.

Comes from [SVS-116](https://jira.sonarsource.com/browse/SVS-116)

**Comment by rickoonk** [comment]
We have this issue right now within our own project. I think it is a big limitation if the local analysis doesn't match with the results from MSBuild. In order to remove the warnings in in Visual Studio we have to suppress all warnings in the source files too. 

When do you guys think this will be embedded in SL?

**Comment by duncanp-sonar** [comment]
Closing this issue - replaced by #1336
