### ISSUE TITLE
When syncing with SonarQube, SonarLint for VS should not touch files if there is no change

### ISSUE THREAD

**Issue by csoltenborn** [SonarSource/sonarlint-visualstudio#198]
This is a duplicate of #147, which I cannot reopen, but is still valid - the according [StackOverflow question](https://stackoverflow.com/questions/43113882/using-sonarlint-for-visual-studio-with-tfs-sharing-rulesets-accross-development) didn't receive any responses.

In a nutshell: We'd like to use SonarQube/SonarLint within our team, but have issues sharing Sonar rulesets, which basically renders Sonar unusable for us. In particular, if SonarLint refreshes our solution's projects' rulesets, TFS reports many outgoing changes although the files' content hasn't changed at all.

**Comment by valhristov** [comment]
Hi @csoltenborn, indeed, SonarLint will "touch" the files when the `Update` context menu command is clicked, thus marking them as modified in TFS. We did not consider this as a problem before, because once you configure your quality profile you rarely need to update it from SonarQube, but we agree that the behavior is annoying.

I slightly updated the text of the issue and we will consider it for development in the near future. Unfortunately I cannot give an exact timeframe when this will be fixed.

**Comment by michalb-sonar** [comment]
Another user with the problem where the files are touched when there is no change (see commit details): https://github.com/SonarSource/sonarlint-visualstudio/issues/413#issuecomment-338954634

**Comment by Evangelink** [comment]
This is no longer relevant when using the new connected mode.

**Comment by connectinghub** [comment]
I am facing the exact same issue as reported by @csoltenborn, where the ruleset files are "touched" and get checked-out automatically, even when then has been no change in the quality file on the server.

@Evangelink mentioned that this issue is no longer relevant in connected mode. However, I am using connected mode with -
VS version 15.3.4
SonarLint version 3.10

Any help will be highly appreciated.

**Comment by Evangelink** [comment]
Hi @csoltenborn,

We are about to release a new version of the connected mode which is no longer going to install the NuGet hence why I closed the ticket as no longer relevant.

**Comment by connectinghub** [comment]
@Evangelink Do we have a release date ?

**Comment by connectinghub** [comment]
@Evangelink Thanks for the quick reply. I will check it right away !
