### ISSUE TITLE
Massive footprint on my Visual Studio solution after SonarLint setup

### ISSUE THREAD

**Issue by aureole82** [SonarSource/sonarlint-visualstudio#2221]
I've just installed
![image](https://user-images.githubusercontent.com/4819891/110626117-9df8a280-81a0-11eb-8c33-01777211ef0b.png)
on latest Visual Studio 16.9.1

and SonarLint messed up ALL my 57 project files with:
```xml
  <PropertyGroup>
    ...
    <CodeAnalysisRuleSet>..\.sonarlint\my-projectcsharp.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  ...
  <ItemGroup>
    <AdditionalFiles Include="..\.sonarlint\my-project\CSharp\SonarLint.xml" Link="SonarLint.xml" />
  </ItemGroup>
```

Is this really necessary? Couldn't the _my-projectcsharp.ruleset_ remain on the server? What's the benefit of a local copy? What happens if the ruleset changes on the server? Isn't _SonarLint.xml_ just a local configuration file which doesn't have to be checked into the repository? Why don't you distinguish between local and team-shared files like ReSharper or other Visual Studio extensions do?  Why don't you update the _.gitignore_ accordingly? What's the benefit of a linked _SonarLint.xml_ in ALL 57 projects? Why do you add all those references again when I hit this again?
![image](https://user-images.githubusercontent.com/4819891/110627102-d8167400-81a1-11eb-945b-de729f846807.png)

### Related information

```
Microsoft Visual Studio Professional 2019
Version 16.9.1
VisualStudio.16.Release/16.9.1+31105.61
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional
...
SonarLint for Visual Studio   4.33.0.28535
SonarLint is an extension to your favorite IDE that provides on-the-fly feedback to developers on new bugs and quality issues injected into their code.

```

**Comment by duncanp-sonar** [comment]
@aureole82 most of your questions have been answered in the [community forum](
https://community.sonarsource.com/c/help/sl/11), or in the wiki pages describing [Connected Mode](https://github.com/SonarSource/sonarlint-visualstudio/wiki/Connected-Mode).  According to the _Overview_ section:

> You can connect SonarLint to SonarQube >= 6.7 or SonarCloud to benefit from the same rules and settings that are used to inspect your project on the server. SonarLint then hides in VS the issues that are marked as Won’t Fix, False Positive or Fixed.

The _ruleset_ and _SonarLint.xml_ files are necessary to configure the analyzers so that they produce similar results in the IDE to those reported on the server. See [here](https://github.com/SonarSource/sonarlint-visualstudio/wiki/Connected-Mode-configuration-for--C%23-and-Visual-Basic-projects) for more information.

Connected Mode is optional; the analyzers will still work, using either their default values or any local configuration you provide manually.

If you do want to use Connected Mode, SonarLint will check that generated _ruleset/SonarLint.xml_ files are referenced in each project and re-add them if they are not.

Having said all that, the default way the _ruleset/SonarLint.xml_ settings are added to each project is very noisy and disruptive. There are historical reasons it was done this way, one of which was predictability; MSBuild/VS allow a great deal of flexibility in how projects are laid out and configured, and the method SonarLint uses is noisy but reliably achieves the main goal of correctly configuring the projects.

In fact, SonarLint doesn't care _how_ the generated files are referenced, so long as they _are_ referenced. You can use any other the standard MSBuild mechansims to reference the files without changing every project, some of which are discussed [here](https://github.com/SonarSource/sonarlint-visualstudio/wiki/Choosing-which-C%23-or-VB.NET-rules-to-run-in-Standalone-mode) e.g. by using `Directory.Build.props`, which is what we do in the SonarLint [repo](https://github.com/SonarSource/sonarlint-visualstudio/blob/021c462c5fbe83b99b13a97566483c707dc61370/Directory.Build.props#L8) itself.

At present you'd have to make these changes manually once. We do have a work item in our internal roadmap for this year to re-work the entire binding process to make it simpler.

**Comment by marco-comi-sonarsource** [comment]
Thanks for your feedback @aureole82, we've made a note of it and we'll take it into account to improve binding process in SonarLint.

**Comment by aureole82** [comment]
It's not fair to close this issue I have no chance to track the progress on a wiki site like:
https://github.com/SonarSource/sonarlint-visualstudio/wiki/Choosing-which-C%23-or-VB.NET-rules-to-run-in-Standalone-mode

**Comment by duncanp-sonar** [comment]
@aureole82 please track the epic ticket #1428 instead.
