### ISSUE TITLE
Provide a link where it is possible to report an issue with a C++ analyzer

### ISSUE THREAD

**Issue by Thieum** [SonarSource/sonarlint-visualstudio#2254]
**Is your feature request related to a problem? Please describe.**
I'd like to report a case where a C++ analysis rules seems like a false positive.

**Describe the solution you'd like**
I would like a link in the useful links here: https://github.com/SonarSource/sonarlint-visualstudio#useful-links where I can report this kind of error. Only the C# one is listed there at the moment.

**Describe alternatives you've considered**
I tried to search on github and your website for a way to report or discuss C++ rules, but I didn't find anything like the C# project.

**Comment by rita-sonarsource** [comment]
Hi @Thieum, feel free to open a thread in the [community forum](https://community.sonarsource.com/tags/c/bug/fp/7/cfamily) with your false-positive case. Community forum is the best place to report issues and suggest new features due to higher visibility and a voting system. We'll take a look at mentioning that in the "useful links" section, thanks for the suggestion.
