### ISSUE TITLE
Quickly deactivate / activate the support for additional languages makes VS crash

### ISSUE THREAD

**Issue by christophelevis** [SonarSource/sonarlint-visualstudio#231]
Note also that, when VS crashes, the daemon stays alive

**Comment by janos-ss** [comment]
The crash happens when click on **Deactivate** too quickly right after clicking on **Activate more...**.

Repro steps:

- Open Visual Studio
- Open **Tools** menu, select **Options...**, select **SonarLint for VisualStudio**
- If the **Deactivate** button is visible, click on it to deactivate additional languages
- In a `cmd` window running as admin, count the java processes involved in TCP connections with `netstat -nb | find /c "java.exe"`
- Click **Activate more...**, the button text changes to **Deactivate**, click on it as fast as you can, and Visual Studio will crash
- Check the count again, it probably increased
