### ISSUE TITLE
Guidance on keeping SonarLint + Sonar C# in step?

### ISSUE THREAD

**Issue by davejclausen** [SonarSource/sonarlint-visualstudio#259]
We are testing out SonarLint at our organization.  Developers have installed SonarLint locally; and SonarQube runs quality builds at night (which can flag developers for violations).

A scenario we're seeing is that developers install a version of SonarLint that's later than Sonar C# for SonarQube.  What can happen is, for example, S3881 flags no violations in SonarLint locally (so the developer thinks they're "ok"); but does flag violations in SonarQube.  This is because the rule has iterated/relaxed over time, and our SonarLint is a later version than our Sonar C#.

An additional scenario: we are trying SonarLint in Connected Mode.  But what can happen is a developer updates their SonarAnalyzer.CSharp NuGet.  They find that brand new rules from the NuGet are in-force, even when they update their rules from SonarQube.  This is because the rules exist and are enabled in the NuGet itself, even though they don't exist in SonarQube or in their local .ruleset file.

I think the solution is to tell our developers not to update their NuGet; and for us to update SonarLint and Sonar C# in tandem.  Is there a way to know what version of SonarLint corresponds to what version of Sonar C#?

**Comment by valhristov** [comment]
Hi @davejclausen, the way to enforce the usage of the same version of SonarAnalyzer is connected mode. This way the nuget references and the ruleset will be added to the projects (and source control) and a simple review process or notifications for commits in specific files (should be doable with most SCMs) should be generally sufficient to avoid accidental upgrades.

When in Connected Mode, SonarLint will reference the nugets that correspond to the version of SonarC# that's installed on SonarQube, so even if you have latest version of SonarLint, you could add the nugets of an old SonarC#. In addition, when you have a reference to the nugets, SonarLint will disable the built-in analyzers. In other words, in connected mode you are always analyzing with the version of SonarC# that is installed on SonarQube.

I am not aware of a page that lists the corresponding versions of SonarLint and SonarAnalyzer, but you could check this file for the time being:
https://github.com/SonarSource/sonarlint-website/blob/gh-pages/visualstudio/resources/scripts/App.ts

This file is changed every time we release SonarAnalyzer and SonarLint, and is always up to date. Perhaps this will change in the upcoming months because we are planning to replace the implementation of http://www.sonarlint.org some day.

**Comment by davejclausen** [comment]
@valhristov, that is great information.  Thank you!
