### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by zormaxo** [SonarSource/sonarlint-visualstudio#2960]
I am using SonarLint extension v3.3.3. SonarLint gives **"FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory"** error while analyzing my angular project. I set NODE_OPTIONS, but didn't help.
![SystemPropertiesAdvanced_HGGYy3USry](https://user-images.githubusercontent.com/9765632/160701212-c934ab43-ecae-4969-b257-00cd2c8ed758.png)
I am not using cloud or qube. I think this is an issue that needs to be resolved.

**Comment by rita-sonarsource** [comment]
Hello @zormaxo, SonarLint v3.3.3 for Visual Studio is a 5 years old version. Could you please try updating to the [latest version](https://github.com/SonarSource/sonarlint-visualstudio/releases) and see if that still occurs?

**Comment by rita-sonarsource** [comment]
Hello @zormaxo, this repository is for SonarLint for Visual Studio. Since you mentioned v3.3.3, I assume you meant to open this issue for SonarLint for Visual Studio Code. May I redirect you to our [community forum](https://community.sonarsource.com/tags/c/bug/fault/6/sonarlint)? It would help us to investigate if you could please open your issue there. Thank you.
