### ISSUE TITLE
Resolved Issues not syncing with Sonar Lint Connected Mode

### ISSUE THREAD

**Issue by Paulie-Waulie** [SonarSource/sonarlint-visualstudio#445]
### Description

I have been trying out the recent release of Sonar Lint with the hope that it would start syncing Resolved Issues but nothing really seems to have changed. We have five code smells, 3 that are confirmed and two that are marked as  Resolved Won't Fix , the two marked as Resolved Won't Fix are no longer reported in Sonar Qube (just categorised under Won't Fix), however, they are still shown as build warnings in Visual Studio as they were before along with the three that are confirmed.

Possibly not related bu we're also experiencing an issue where when we open a solution we get the message that the rulesets are out of date, following the update procedure, nothing changes but the message goes away until the next time the IDE is opened.

### Repro steps

1. Write code that violates a Sonar Rule to invoke an analysis build warning.

2. Execute Sonar Qube analysis to see the violation recorded as code smell in Sonar Qube.

3. Mark as Resolved Won't Fix

4. Run analysis again to see the code smell no longer reported in Sonar Qube.

5. Perform a build/rebuild in Visual Studio. Issue still reported as build warning. This is also the case after restarts & re-installation of Sonar Lint.

### Expected behavior

Resolved issues in Sonar Qube are no longer reported by SonarAnalyzer

### Actual behavior

Resolved issues in Sonar Qube are still reported by SonarAnalyzer.

### Related information

We are using:
- VS 2017 - V15.2, 
- Sonar Lint V3.7.0.2645 
- Sonar Qube V6.4.0.25310.

Languages in solution: C#.

**Comment by duncanp-sonar** [comment]
@Paulie-Waulie 

Which version of the SonarC# plugin do you have installed on the server? It needs to be at least v6.5.

"Rulesets are out of date" message: this shouldn't be appearing every time, but as you say if may or may not be related. However, check that you are not being affected by [#378](https://github.com/SonarSource/sonar-csharp/issues/738) issue (upgrading the SonarAnalyzer NuGet package removes the analyzer from the project). This is a NuGet issue, but it might be part of the problem here.

FYI SonarLint will contact the SonarQube server to get an updated list of issues every ten minutes. Alternatively, closing and re-opening the solution will force an immediate re-fetch. However, re-building in VS doesn't trigger a re-fetch.

Regards,
Duncan

**Comment by Paulie-Waulie** [comment]
Hi,

Thanks for the reply.

Good news, this did resolve our issue, sadly I was not aware that we needed to update that aspect of Sonar, I was informed that we only needed to update Sonar Lint to get this feature working but I should have tried updating that before raising the issue.

Bad news, this update seems to have caused a separate issue with dotCover reports, I have raised a new issue here:

[dotCover Issue](https://github.com/SonarSource/sonarlint-visualstudio/issues/450)

Many Thanks
