### ISSUE TITLE
Display the organizations the user is member of

### ISSUE THREAD

**Issue by christophelevis** [SonarSource/sonarlint-visualstudio#446]
When configuring a connection to SonarCloud, SonarLint has to retrieve the whole list of organizations to give the possibility to the user to select the one she's interested in.
As a result, a huge number of organizations are listed which don't make sense for the user. And this operation takes quite a long time.
We should first retrieve and propose the organizations the user is member of and keep the ability to connect to another organization as a fallback option.

Depends upon [SONAR-9000](https://jira.sonarsource.com/browse/SONAR-9000 ).

**Comment by valhristov** [comment]
This is implemented unconditionally and there is no way to fallback to the old way of selecting an organization. We need to discuss with @christophelevis if we want to add the fallback or leave it as it is.

**Comment by josundt** [comment]
What's happening here?
It is inconvenient and probably not a good idea from a security perspective to allow anyone to enumerate all SonarCloud customers.
I was surprised that my Personal Access Token allowed me to do that, I expected to only be shown the customers/projects that my user account is connected to.

**Comment by cbuchanan** [comment]
@duncanp-sonar that may be the case (although @josundt is correct), the question still stands. It would appear that a commit was made on this issue a year ago and yet when I link a project in VS SonarLint to SonarQube using a PAT, all organizations are shown. Ignoring the data security issues for a moment, the performance impact is significant and unresolved.

**Comment by duncanp-sonar** [comment]
@cbuchanan yes, that's why this ticket is still open.

**Comment by cbuchanan** [comment]
@duncanp-sonar I understand that. :) My point though is that @josundt was asking what the status on this ticket is since it hasn't seen any activity in a long time, and presumably if there's an ETA on the fix - and if he's not intending to ask that, I'm wondering that myself.

**Comment by josundt** [comment]
The intent of my original question was also about ETA 😉.

**Comment by duncanp-sonar** [comment]
Time permitting, we'll work on this ticket as part of v4.11, due to finish on 12/07/19.

**Comment by DanielBMann9000** [comment]
I don't see that this is fixed in 4.11. Connecting to https://sonarcloud.io with an auth token still lists all projects. I am a member of an organization with private projects.

**Comment by duncanp-sonar** [comment]
@DanielBMan9000 this project was about changing the list of organisations you see when connecting. In v4.11 you should see a 'Select an organisation" with two tabs, one with a drop-down listing only your organisations. Is this what you are seeing?

**Comment by DanielBMann9000** [comment]
I have a dialog box to connect to SonarQube. It takes a URI, a username/token, and a password.

When I connect to SonarCloud, it freezes for about 5 minutes, then displays a massive list of projects which are not relevant to me. At that point, Visual Studio's CPU usage is pegged at 100% and is unusable until I kill it, which brings me back to square 1.

**Comment by duncanp-sonar** [comment]
Is it a list of projects or a list of organisations? (the title of the dialogue will tell you).

That sounds like the old version. Please double-check the version of SLVS you have installed.

Also, which version of VS are you using?

**Comment by DanielBMann9000** [comment]
There is no dialog at the point where I see the list. It is a "Connections" section with a single root element labelled "https://sonarcloud.io", containing a massive list of what appear to be projects.

The version is 4.11.0.0. I'm using Visual Studio 2019. It was installed from the extensions management area in VS.

**Comment by duncanp-sonar** [comment]
@DanielBMann9000 thanks for the info.

The expected sequence is as follows:

**Step 1:** enter the server URL and credentials
![image](https://user-images.githubusercontent.com/10757559/61357554-6a9d2d80-a870-11e9-89f1-1b912f23e355.png)

**Step 2:** select the organisation
![image](https://user-images.githubusercontent.com/10757559/61357571-71c43b80-a870-11e9-9347-2a810d3a1c37.png)

**Step 3:** select a list of projects from within that organisation
![image](https://user-images.githubusercontent.com/10757559/61357612-830d4800-a870-11e9-887d-1348f4c53082.png)

If I understand correctly, you're going straight from step 1 to step 3, with a long delay and a very long list of projects. Is that correct?

I can't repro that behaviour with any valid/invalid tokens I've been able to create.
Could you try revoking your token and generating a new one?

**Comment by DanielBMann9000** [comment]
That's correct -- I don't see step #2. I've revoked and regenerated my token several times.

**Comment by josundt** [comment]
> @josundt my understanding is that that behaviour of the SonarCloud APIs is by design, in the same way that GitHub API allows GitHub users to be enumerated. 

@duncanp-sonar The main problem now is that all SonarCloud organizations are listed step 2 since the SonarCloud API is designed this way.

It was a bit unclear to me what is being fixed here.
 
Whether it is a security concern or not, the VS extension suffers from terrible performance when connecting to SonarCloud because it takes too long time to wait for the huge API response containing all SonarCloud organizations/customers.

**The SonarCloud API should support getting organizations filtered by the user identified by the PAT** - only organizations that the user is connected to should be returned. 

The VS extension should use this API method instead.

**Comment by cbuchanan** [comment]
@duncanp-sonar in testing the new version I think I'm seeing what @DanielBMann9000 is seeing. After entering my PAT and the SonarCloud URL, SonarLint is skipping the organization dialogue entirely and going to "retrieving projects". After selecting the organization, loading the list of projects used to be incredibly fast, but now it's taking minutes - in fact, it took 8 minutes. The (bigger) problem is that it's now showing a list of projects that are outside of my organization - a significant data leak in the API.

I'm wondering if the SonarCloud change to remove the unused personal organizations have affected the workflow? My account is now only associated with a single private organizaiton, and maybe that's causing step 2 to somehow be skipped. Regardless though, data security on projects in other organizations shouldn't require the client to specifically filter that data out. If they're projects in public organizations then the leak isn't so bad, but with that list of projects showing up in SonarLint it's now impossible to filter the list of projects to ones that are just part of my organization. The functionality is now actually worse because my users can't find the project to bind to.

**Comment by DanielBMann9000** [comment]
> My account is now only associated with a single private organizaiton, 

Same here. I'm glad I'm not alone in seeing this behavior.

**Comment by duncanp-sonar** [comment]
> I'm wondering if the SonarCloud change to remove the unused personal organizations have affected the workflow? 

@cbuchanan You're right. Thanks for the suggestion. I've created a separate bug to track this: #937.
I'll aim to release a bug fix version tomorrow.

> The (bigger) problem is that it's now showing a list of projects that are outside of my organization.

They are all public projects: no private data is being leaked.


@josundt:
>The SonarCloud API should support getting organizations filtered by the user identified by the PAT

Filtering to the user's organizations is now supported by the API. The dialogue is step 2 now only displays the user's organizations. That's the issue described in this bug, and that is what was fixed in v4.11.

Unfortunately, the combination of fixing this bug and the deletion of personal organizations has uncovered another bug which means the dialogue is skipped and all public projects are retrieved. I missed this during testing. Apologies for the inconvenience.

**Comment by duncanp-sonar** [comment]
FYI [v4.11.1](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v4.11.1.10027) has been released.

**Comment by josundt** [comment]
Works like charm 👍

**Comment by duncanp-sonar** [comment]
@josundt Great! Thanks for lettings us know.

cc @christophelevis
