### ISSUE TITLE
v7 connected mode lost ability to centrally manage connected mode configuration

### ISSUE THREAD

**Issue by rjgotten** [SonarSource/sonarlint-visualstudio#4514]
With the new connected mode settings being moved to store in individual Windows user profiles' Appdata folders, centrally managing configuration and updates to connected mode bindings and ensuring they are kept up to date and are set up for users has become impossible.

This adds additional weight to onboarding new team members, who now have to manually configure and bind SonarLint and it can potentially lead to problems whenever solutions change and add additional projects that need to be bound; etc.

I can respect that some developers would want less 'noise' in their source control, but storing connected mode settings in the user profile or locally with the projects itself should have been a configured choice.

As is, the current situation is a functional regression and a productivity setback.

**Comment by duncanp-sonar** [comment]
cc @marco-comi-sonarsource

**Comment by marco-comi-sonarsource** [comment]
Thanks for your feedback @rjgotten - we're aware indeed that this change would have an impact if you relied on sharing configuration via source control between contributors. We're going to look at ways to make connected mode onboarding less painful in the near future, could you confirm that the settings you'd like SonarLint to automatically pick up are:
- the SonarQube server URL
- the SonarQube projectKey
I am asking because one of the possibilities could be to introduce the possibility to read those settings from a configuration file optionally committed with the project files while leaving all remaining contents generated by SonarLint (e.g. the quality profiles downloaded from SonarQube) in the individual Windows user profiles' Appdata folders

**Comment by rjgotten** [comment]
Yes. Those would be the settings that are most relevant.
Rule overrides as far as they are needed (e.g. because we specifically don't want to use one particular rule that's part of the default Sonar way profile, but we also don't want to split from it) can be handled via `.editorconfig`.

Note though; it might be beneficial to also store some kind of key property in such a config file, because of concerns raised in #4515

**Comment by tbutler-qontigo** [comment]
> we're aware indeed that this change would have an impact if you relied on sharing configuration via source control between contributors. We're going to look at ways to make connected mode onboarding less painful in the near future

Just a thought - perhaps changes like you have made and changes you are considering which may impact how companies use your product, particularly "at scale" should be put out for discussion / user input *before* making the change vs making "breaking" changes and then looking at ways if minimising the pain.

As a minimum they should be optional for at least a period of time and then reverted or made the one and only option, depending on the feedback you get from your users.

**Comment by pascalberger** [comment]
Same issue here. This changes makes SonarLint, and in the end SonarCloud, for us useless for two reasons:

1. Every developer needs now to bind locally to the correct Sonar project (previously only required to define credentials)
2. Compiling using CLI no longer will use the Sonar ruleset

**Comment by tbutler-qontigo** [comment]
> 2. Compiling using CLI no longer will use the Sonar ruleset

This is a definite step backwards - loss of functionality.   
Arguably central management of the profiles might be considered a bit of an "edge" case and therefore not necessarily to be catered for (though some discussion would still have been nice) but compiling using the CLI is highly unlikely to be an edge case....so to now have different experiences depending on which tool you use to compile your code is...less than ideal

**Comment by dtemme** [comment]
For our company, this is also a big step backwards. We are a team of ~35 developers and we have a lot of small repositories.
Previously the people didn't need to connect to SonarQube and most of them didn't need to know a lot about SonarQube. It just worked because we configured it once and all the configuration was part of the repository.
With your latest changes, I have to spend a lot of time to explain everyone how to create Personal Access Tokens and how to connect to to SonarQube. This is very disappointing and error prone.

**Comment by marco-comi-sonarsource** [comment]
> Previously the people didn't need to connect to SonarQube and most of them didn't need to know a lot about SonarQube. It just worked because we configured it once and all the configuration was part of the repository.

> Every developer needs now to bind locally to the correct Sonar project (previously only required to define credentials)

@dtemme, @rjgotten, @pascalberger can you confirm that you use individual user tokens for each developer?
We'll consider ways to restore the ability to share connection settings (server URL, project key) but each developer would be required (like before the release of v7.0) to manually set up its personal token at least for the first solution they bind to SonarQube. So actually the ability to automatically set up connected mode without intervention from the developer would work starting from the second solution being setup within a Visual Studio installation.

> Compiling using CLI no longer will use the Sonar ruleset 

> compiling using the CLI is highly unlikely to be an edge case....so to now have different experiences depending on which tool you use to compile your code is...less than ideal

@tbutler-qontigo, @pascalberger could you detail a bit more about what functionality are you missing when compiling in CLI? Do you want to see Sonar warnings as an output of the compilation? In this case, how are you going to process them and what do you do with the output? If you need a CLI tool to analyze your whole project, have you considered using [SonarScanner for MSBuild](https://github.com/SonarSource/sonar-scanner-msbuild) instead?

**Comment by pascalberger** [comment]
> > Previously the people didn't need to connect to SonarQube and most of them didn't need to know a lot about SonarQube. It just worked because we configured it once and all the configuration was part of the repository.
> 
> > Every developer needs now to bind locally to the correct Sonar project (previously only required to define credentials)
> 
> @dtemme, @rjgotten, @pascalberger can you confirm that you use individual user tokens for each developer? We'll consider ways to restore the ability to share connection settings (server URL, project key) but each developer would be required (like before the release of v7.0) to manually set up its personal token at least for the first solution they bind to SonarQube. So actually the ability to automatically set up connected mode without intervention from the developer would work starting from the second solution being setup within a Visual Studio installation.

Yes, in our case every developer uses its own user token.

> > Compiling using CLI no longer will use the Sonar ruleset
> 
> > compiling using the CLI is highly unlikely to be an edge case....so to now have different experiences depending on which tool you use to compile your code is...less than ideal
> 
> @tbutler-qontigo, @pascalberger could you detail a bit more about what functionality are you missing when compiling in CLI?

We need to separate here how you market as SonarLint nowadays and how it technically works. In the beginning SonarLint was a Visual Studio extension providing connected mode to have rulesets automatically synchronized to the project. This allowed to use Sonarqube/cloud as place for central rule set management, and SonarLint was responsible to keep ruleset of projects up to date with the central configuration. The actual rules are implemented in the SonarAnalyzer.CSharp NuGet package, which is a standard Roslyn Analyzer, which can be used of its own without any other Sonar products. In the beginning SonarLint, as part of the ruleset synchronization, also made sure to add the required analyzers to the project files. Once this synchronization was done, everything was pure standard .NET: A project, including some analyzer assemblies and ruleset files. I could compile this project in Visual Studio, using `msbuild`, `dotnet` or whatever .NET ecosystem has to provide. This worked perfectly fine for my use cases and was all I needed.

At some point Sonar started to move and market their products in a direction which doesn't bring any additional features, but vice-versa removed one feature after another, for my use cases. It started with SonarLint no longer adding Analyzer to the csproj, but injecting them through MSBuild targets in the build process in Visual Studio. Which means that if I don't manually add the analyzer to the project, I will get different results when building using `msbuild` or `dotnet`. Now next step comes with removal of the ruleset, meaning that adding the analyzer no longer will work, and use case is completely broken. 

> Do you want to see Sonar warnings as an output of the compilation? In this case, how are you going to process them and what do you do with the output? If you need a CLI tool to analyze your whole project, have you considered using [SonarScanner for MSBuild](https://github.com/SonarSource/sonar-scanner-msbuild) instead?

My decision to use SonarCloud was based on the fact, that it plays well with the .NET ecosystem. IMHO this is gone nowadays completely, and Sonar tries to build their own ecosystem, where I honestly don't even any longer now what the actual use case for using SonarQube/Cloud is. You market SonarLint as `an advanced linter in your IDE for Clean Code`: I will never want a linter for my IDE. I need linters for my codebase, independently how the code is built, and I expect them to work in all scenarios (IDE, CI, etc), using its ecosystems standard tools (in case of .NET e.g. the `dotnet` CLI). I don't wan't to see `Sonar warnings` (whatever this shoud be) in the output, I expect warnings and errors from the `SonarAnalyzer.CSharp` Roslyn analyzer be reported the same way when compiling in Visual Studio or using `dotnet` CLI. I would never use SonarScanner for MsBuild as CLI tool, since I want to use standard ecosystem tools and there is no reason for it as long as I'm not interested in the server-side Sonar rules (which I'm not except in CI scenarios where I use it).

**Comment by rjgotten** [comment]
> @dtemme, @rjgotten, @pascalberger can you confirm that you use individual user tokens for each developer?
Yes. Unique credentials for every developer.

**Comment by tbutler-qontigo** [comment]
One of the issues we face is that we have a lot of code that is shared using project references. 
We don't want to report the same issues over and over again in every solution that references these shared projects - and with a very mature codebase, there is a lot of issues.

We have until now been using conditionals in our .csproj files to include the sonarlint bindings only in the solutions which "own" the shared code so that we do not see those issues everywhere.

Now that the bindings have moved out of the .csproj file, we cannot do that.
It is not feasible to ask 100 developers to customise their setup for 50+ solutions to get back the experience they had before - even if I knew what to tell them to do in order to achieve that.

It may simply be that we have to tell people not to use SonarLint at all because they will be overwhelmed with "shared" issues in every solution and so will not be able to see the only the issues that actually matter to them.

**Comment by marco-comi-sonarsource** [comment]
@tbutler-qontigo When working on a solution that imports a shared project without "owning" it, do you want to see no SonarLint issues reported at all for that project? Is it correct to say that you'd like to totally disable SonarLint for the projects included in the solution that are not part of the SonarQube project you're connecting to?

**Comment by tbutler-qontigo** [comment]
Hi
Correct.
lets say we have a solution with `Project A` and `Shared Project B`
We would want to see issues for `Project A` but not `Shared Project B`
So `Shared Project B` would only include sonar lint files when the SolutionName is the name of the "owning" solution.
Similarly we would have `SonarQubeExclude` and other related properties set different ways depending on if the solution is the "owning" solution or not.

The idea is for any given project to only be analyzed once, as part of one solution, and as part of one SonarQube project

**Comment by WillEllisBH** [comment]
Ditto to what @tbutler-qontigo said. Sonar supports having multiple sonar projects within one repo. If there is a csproj scanned in one sonar project, but then also included in the solution thats scanned by another project via a project reference, we have filtered this to exclude that project in sonarcloud scans but then on the sonarlint side it has the csproj reference to its own sonar ruleset so we still expect the sonarlint extension to lint with the rules of that other project. Same for even if you just have multiple sonar projects for one mono repo. 
Having some sort of reference in the csproj allowed for these situations. I like the removal of the .sonarlint folder, as that quite rightly should be pulled down by the extension to some user data folder, but the csproj should still be able to have some sort of reference to the sonarcloud project that it is scanned within. I.e. maybe rather than <CodeAnalysisRuleSet> being a relative path to a .sonarlint folder it could be the id of the sonar project the csproj should pick up the ruleset from. Then when you connect the extension it could grab all your rulesets and know which to use per csproj based on the id.

**Comment by tbutler-qontigo** [comment]
Hello 
Thanks for sharing some details of your plan - it sounds like you have no plans in any reasonable timescale to support teams who have shared code/mono repos and do not want to have every solution reporting the same issues with that shared code by bringing back features that worked well in the pre-7.0 world.

Is there any way to force VS to install the older version so we can get this back or do we just need to abandon SonarLint now?

thanks

**Comment by duncanp-sonar** [comment]
@tbutler-qontigo

> Is there any way to force VS to install the older version ...?

Older versions of SonarLint are available from the [releases](https://github.com/SonarSource/sonarlint-visualstudio/releases) page of this repo. Make you sure remember to uncheck `Automatically update this extension`:

![image](https://github.com/SonarSource/sonarlint-visualstudio/assets/10757559/7210f72f-fd6c-4a08-88e2-8a1f0804fcd5)

**Comment by tbutler-qontigo** [comment]
Sanity restored, thanks @duncanp-sonar 
Hopefully we can limp along with version until you restore the missing features to support mono-repo environments

**Comment by WillEllis** [comment]
Any update on this? @duncanp-sonar

**Comment by WillEllisBH** [comment]
Any update on this @duncanp-sonar ? This is still a blocker for us with multiple sonar projects mapping to one repo with project references.

**Comment by marco-comi-sonarsource** [comment]
We've actually started working on the option to automatically set up the connection to SonarQube based on the configuration generated by one contributor and committed together with the project files, you can expect news in a matter of weeks. 

> the newer SonarLint allows us to focus on new/changed code rather than seeing thousands of issues in a code base 10+ years old
Please note that [we released](https://community.sonarsource.com/c/sl/sonarlint-releases/37) this feature for some IDEs but not for Visual Studio yet.

**Comment by tbutler-qontigo** [comment]
> Thanks for sharing some details of your plan - it sounds like you have no plans in any reasonable timescale to support teams who have shared code/mono repos and do not want to have every solution reporting the same issues with that shared code by bringing back features that worked well in the pre-7.0 world.

Is this going to bring back support for mono repo/shared code scenarios where teams do not want to have every solution reporting the same issues with that shared code (new or otherwise) so we can once again have only one solution reporting same and all other solutions that reference the shared code will only report issues unique to the projects in that solution?

**Comment by marco-comi-sonarsource** [comment]
I'd like to share an update on the first feedback raised in this issue:

> With the new connected mode settings being moved to store in individual Windows user profiles' Appdata folders, centrally managing configuration and updates to connected mode bindings and ensuring they are kept up to date and are set up for users has become impossible.

We've just released a new SonarLint version that officially supports this workflow; more details [here](https://community.sonarsource.com/t/sonarlint-for-visual-studio-7-4-save-and-share-your-connected-mode-setup/104455/1).

**Comment by dtemme** [comment]
Thank you @marco-comi-sonarsource. The solution seems to work partially.
I configured the shared configuration via the dialog (all existing settings have been removed and I committed the .sonarlint/<solution>.json). My colleague checked out the changes and opened the solution. But there was no banner asking him to connect as described in the documentation. He has to manually open the the options dialog (Extensions -> SonarLint -> Connected Mode -> Bind to ...). Only if he selected this menu, the banner pops up.

We are both on the latest version of SonarLint 7.4.0.80741 and Visual Studio 17.8.0.

**Comment by marco-comi-sonarsource** [comment]
Hi @dtemme, thanks for reporting this. Could you double-check whether you allowed enough time for all the modules to load when you opened your solution? Sometimes it takes some time to load, delaying the gold bar's display. If it still does not appear, we would appreciate it if you could open a thread [here](https://community.sonarsource.com/c/sl/visual-studio/35) for our teams to investigate.
