### ISSUE TITLE
Unsupported offline installer for additional Languages 

### ISSUE THREAD

**Issue by EyalZilberblum** [SonarSource/sonarlint-visualstudio#558]
### Description

After Downloading and installing SonarLint Extension for Visual Studio (2015), the install of additional language fail because there is no connectivity to repo1.maven.org

### Repro steps

1. Make sure that you don't have any network connectivity
2. Install SonarLint Extension for Visual Studio
3. Install the additional languages

### Expected behavior

The SonarLint-Daemon should be bundled with the SonarLint Extension

### Actual behavior

The SonarLint Extension tries to download the Daemon from here: http://repo1.maven.org/maven2/org/sonarsource/sonarlint/core/sonarlint-daemon/{0}/sonarlint-daemon-{0}-windows.zip

### UPDATE
From [v4.12,](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v4.12.0.10191) the C/C++ analyzer is included in the VSIX so no additional installation is required.
Currently, the only language that requires additional files to be download is JavaScript.

### Known workarounds

Compile the SonarLint extension from source after changing the URL mentioned above to one that valid in my network.

source file to make the change in: src\Integration.Vsix\SonarLintDaemon\SonarLintDaemon.cs LINE:43

The best solution is to bundle the Daemon with the extension, but expanding the download URL in the xaml would be good as well - this way the user can provide his own path to the daemon.

### Related information

* SonarLint for VS Version - LATEST
* Visual Studio Version 2015 / 2017
* SonarQube server version LATEST(6.7.1)
* Languages in your solution (C#, VB.Net, Javascript, C, C++)

**Comment by Evangelink** [comment]
Hi @EyalZilberblum,

Thanks for the feedback. Your suggestions are interesting! We decided (at least for now) not to bundle the daemon with SonarLint because of its size.

We have received quite a lot of different feedback on this topic (mainly in the lines of we need to change this behavior) and we will surely change the current behavior but we haven't decided what to do yet (which also means that I cannot commit on any release date).

**Comment by elamid** [comment]
I do agree that workstation admins need a package to install the Visual Studio extension, with components for all supported languages, unattended … Actually silent install is done using VSIXInstaller, but 1) the SonarLint additional languages popup conflicts with Visual Studio first use window, and 2) we don't want all our developers having to select their own install options for SonarLint.
I do understand keeping the VS extension small when installed from the VS marketplace, but you should also provide a full silent installer for those who build their development workstations unattended.
Regards,
Eric.

**Comment by plangevin** [comment]
Offline install is really important for us.

I agree with @elamid that users should not manually have to install other things in order to make things work.

But at least, a manual workaround should be available...

**Comment by fbyrne** [comment]
Hi, 
I have a similar issue working behind a corporate gateway which scans all zips for viruses and threats.
This takes a long time >300s at time of writing this.
Where should this daemon be downloaded and extracted to?

Kind regards, 
Fergus

**Comment by valhristov** [comment]
Disclaimer: use the following instructions on your own risk. The paths could change without notification. We don't support offline installations yet and we would strongly recommend waiting for us to release this feature. Every time a new SonarLint for Visual Studio (SLVS) is released the daemon version could change and you will have to install it again.

Having said that, you could actually see where the daemon is extracted to from the source code:
https://github.com/SonarSource/sonarlint-visualstudio/blob/master/src/Integration.Vsix/SonarLintDaemon/SonarLintDaemon.cs#L260

Basically, each release SLVS has a hardcoded link to a version of the daemon. SLVS since version 4.5 uses daemon 3.9.0.1892 (you could see the other versions from the history), the next week we will release SLVS 4.8 which will use daemon 4.0.2.2142.

SLVS considers the daemon installed if the following file exists:
%LOCALAPPDATA%\SonarLint for Visual Studio\sonarlint-daemon-{0}-windows\jre\bin\java.exe

where {0} is the corresponding version of the daemon.

If the daemon is not installed, SLVS downloads this ZIP file:
http://repo1.maven.org/maven2/org/sonarsource/sonarlint/core/sonarlint-daemon/{0}/sonarlint-daemon-{0}-windows.zip

where {0} is again the corresponding version of the daemon and then extracts its contents to the folder above.

**Comment by nebulous999** [comment]
Yes offline language install (C++) is very important for us as well.  We use VS2017 and 2019, and (as yet) no SonarQube server connected.

Also, not sure if this is related, but nothing at all happens when I click "Open description of rule" in the Error List window.  I'm unclear on where that description is supposed to open... is that also because I'm offline?

**Comment by duncanp-sonar** [comment]
@nebulous999, the latest version of SLVS ([v4.12](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v4.12.0.10191)) embeds the C++ analyzer directly in the VSIX. There is no need to download additional files for C++ (although it is still necessary for JavaScript).

The rule descriptions are links to https://rules.sonarsource.com/cpp so you won't be able to see them if you are offline. I've added a feature suggestion for this: #1021

**Comment by nebulous999** [comment]
@duncanp-sonar, thanks for that, it's working great now.
