### ISSUE TITLE
Disable SonarLint analysing every file

### ISSUE THREAD

**Issue by Paulie-Waulie** [SonarSource/sonarlint-visualstudio#573]
### Description

We are introducing SonarLint to our projects over time. We had one recent project which used it from the start and we can feel the benefit, especially with the synchronisation with SonarQube so the analysis is the same locally as it is in our pipeline. This project has only two current code smells reported in the IDE and we have confirmed those as tech debt and will rectify soon. 

Older projects used FxCop and StyleCop. What is proving to be quite an annoyance for our engineers is that when we open a file for one of those older solutions we are bombarded with rule violations as the file is being parsed upon opening. I believe this is intended behaviour, however it really not desired for us. I cannot find a way to disable this within the Visual Studio options. Until some of the solutions are moved over to Sonar and bound to a quality profile with our own defined rule sets using connected mode we do not want Sonar performing any analysis. The engineers are working with different analysis tools for these projects so the fact another tool is running without being requested is frustrating, especially as some of these rules may not be enabled in our quality profile for the solutions actually using SonarLint connected mode.

The only way I have found to disable this behaviour is to disable the SonarLint extension for Visual Studio which is undesired as we do work on solutions where we want/need the extension to be working for binding and updating rulesets.

### Repro steps

1. Open a solution that is not using SonarLint connected mode and not bound to a SonarQube project and does not have the Sonar Roslyn Analyzer installed.

2. Open a file which has some code violations, for example we use Event Sourced aggregates where we have private members which Update State, they have the event type as an argument but the method body does not always use the event parameter as it is just updating an internal model due to the fact the event is present in the stream. This is flagged as rule S1172. Closing the file removes the error from the error list in Visual Studio.

### Expected behavior

A mechanism to disable on access analysis from the SonarLint extension.

### Actual behavior

No way to disable to the analysis without disabling the extension.

### Known workarounds

Disabling the extension temporarily.

### Related information

* SonarLint for VS Version - 3.10.0.3095
* Visual Studio Version - 15.2 (26430.13)
* SonarQube server Version 6.7 (build 33306)
* Languages in your solution - Just C#

**Comment by Evangelink** [comment]
Hi @Paulie-Waulie,

Maybe this won't totally answer your question but have you tried adding a ruleset to each of your projects un-selecting all rules from SonarAnalyzer? The ruleset definitions are respected by SonarLint for VS even in standalone mode.

I would still consider having some of the critical rules enabled just to be sure you don't miss `NullReferenceException` or others bad bugs but I can understand you might still disable them.

**Comment by Paulie-Waulie** [comment]
Hi Evangelink,

Thanks for your reply but I'm not sure what that really solves. As previously mentioned, these are solutions that are currently covered by other static analysis tools, the example rule violation that I gave in my original post will have been suppressed in those tools in those specific cases where the rule was not applicable, therefore we are covered already for a vast majority of code smells and bugs. The reason we are moving to SonarLint is for the connected mode so that Server and Local analysis is the same and we have audit trails for Resolutions, rather than engineers simply adding to suppression files.

Most likely the solutions will be migrated to use Sonar with SonarLint connected mode in the near to medium term future but we have a lot of solutions and teams. I'm not really keen on creating empty rulesets in a solution where we are not actually yet wanting to use the tool, this will be time consuming, especially as at some point they will be migrated to use the quality profiles defined in SonarQube.

We only installed the SonarLint extension for the ability to use connected mode, when we bind a project the Roslyn analyzer is added to the project and the rulesets are added, respecting the quality profile we have defined. We don't really have any desire for the on access file analysis to occur at the moment which is why I was surprised to find that the functionality could not be disabled.

Many Thanks

Paul

**Comment by Evangelink** [comment]
If I correctly understand you would like to have some kind of start/stop or pause analysis so that even the standalone mode doesn't run any analysis? If that's it we don't offer such option yet but this is something I'd like to provide so this would be a good opportunity to start a discussion.

If I am still outside of what you expect, could you give me some idea(s) of what you want to have?

**Comment by Paulie-Waulie** [comment]
Hi Evangelink,

Thanks for your response. That is exactly what I was hoping for. For us, connected mode and standalone mode are quite separate use cases, one is a traditional linting tool and one is allowing immediate analysis in the IDE that matches 100% with the analysis performed on a server. Therefore it would have been nice to have the features separated, either by separate extensions or simply through options in the extension.

This would just make life a lot simpler and less noisy for our engineers when they will work in solutions that are using Sonar Connected mode and solutions that are using other analysis tools that have already been configured until all solutions are migrated to Sonar Connected mode.

We are now looking at moving all of our solutions as fast as we can to avoid friction and potential resistance/negativity to SonarLint when we start to roll it out to all the teams. We were just hoping to not have to do as much work up front.

Many Thanks

Paul

**Comment by Evangelink** [comment]
@christophelevis Could you have a look at this proposal and let me know if that's something we should consider?

**Comment by duncanp-sonar** [comment]
@Paulie-Waulie,

We are trying to keep the behaviour of SonarLint as consistent with the normal behaviour of analyzers in Visual Studio as possible. SonarLint embeds the SonarC# and SonarVB analyzers, so Visual Studio will automatically run them for all projects. Analyzing files as they are opened is the expected Visual Studio behaviour, and there isn't a programmatic way we could disable this for SonarLint using the standard VS extension APIs (in fact, the standard behaviour is that files will be analyzed even if they haven't been opened if you have [enabled full solution analysis](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-enable-and-disable-full-solution-analysis-for-managed-code?view=vs-2017) in _Tools_, _Options_).

It's fair to say that our thinking about how SonarLint should be used wasn't consistent across the main IDEs (Visual Studio, Eclipse and IntelliJ), and has also changed over time.

In particular, the approach taken in SonarLint for Visual Studio ("SLVS") differed from the other IDEs in that it was more heavily influenced by enterprise team scenarios (partly because it was developed in conjunction with the Visual Studio Enterprise development team at Microsoft). That's why Connected Mode installed the Sonar analyzer NuGet packages in every project - that way, even if developers don't have SonarLint installed, a central authority could bind the projects and effectively force developers to run the analyzers in their IDEs.

Our view now is that installing SonarLint is mainly an individual developer's choice - if they find it useful, they can install it and use Standalone mode, regardless of whether their organisation is using SonarQube/SonarCloud or not. Connected Mode gives the added ability to synchronise the rulesets with Quality Profiles automatically, and to receive notifications from the server.

One consequence of this that we have changed the behaviour of connected mode in SonarLint v4 so that it no longer adds the Sonar NuGet analyzers to every project (this was done as a result of feedback that having the packages in every project slowed the build on the developers local machines, and involved multiple file updates when a new version of the analyzer was released). SonarLint now uses the version of the analyzers shipped with the VSIX for connected mode as well as standalone mode.

It's also fair to say that we didn't consider a gradual adoption scenarios like the one you describe, where developers want to analyze some projects but not others. It's possible to manually configure projects to work the way you want, but that's painful for a large number of projects so that's what you're trying to avoid. As I mentioned above, I don't think there is an easy way to achieve that using the available VS extension APIs when shipping the analyzers in the VSIX.

I realise that this doesn't help with your particular scenario, but I hope it does give some insight into why SonarLint behaves the way it does.

Kind regards,
Duncan

**Comment by Paulie-Waulie** [comment]
Hi @duncanp-sonar , 

Thanks for taking the time to write such a lengthy response.

For us, the idea was that we wanted the exact same warnings to fire in the IDE as they would on the server. For us, there is nothing more frustrating than having inconsistencies between local dev and build servers and we thought that was the exact problem SonarLint with connected mode was trying to solve. However, we were not going to jump in with both feet for many, many solutions immediately.

Sadly, we have abandoned SonarLint completely. After trialling it with a few solutions we deemed that it was not appropriate to use across multiple teams and dozens of solutions. The main concerns raised were issues such as this, problems with connected mode synchronisation and the need to have warnings as errors off to support the Sonar flow.

We have gone back to other analysers for our local and build server analysis with Sonar used purely for trend analysis, which is a great shame, we hoped to have everything under one roof with a friction-less experience to really promote engineers to get on board with the notion of "Continuous Inspection".

Many Thanks

Paul

**Comment by StevenTCramer** [comment]
How about adding the analyzers via Nuget package vs VSIX like FXCopAnalyzers does so then I can turn them on project by project by just adding the reference.

**Comment by awjanb** [comment]
> How about adding the analyzers via Nuget package vs VSIX like FXCopAnalyzers does so then I can turn them on project by project by just adding the reference.

This would indeed be the right solution. Or, for the VSIX, add a property page inside Code Analysis where it can actually be configured per project.

**Comment by duncanp-sonar** [comment]
FYI recent versions of Visual Studio 2019 now support enabling/disabling VSIX analyzers per project - see [the MS docs](https://docs.microsoft.com/en-us/visualstudio/code-quality/disable-code-analysis?view=vs-2019).

**Comment by awjanb** [comment]
This doesn't help with the SonarLint C++ extension though
