### ISSUE TITLE
SonarLint for Visual Studio 2017 plugin does not respect shared imports

### ISSUE THREAD

**Issue by t03apt** [SonarSource/sonarlint-visualstudio#658]
[SonarLint for Visual Studio 2017](https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2017) does not work well with shared imports.

I am using [Directory.Build.props](https://github.com/t03apt/sonarlint-visualstudio-tests/blob/master/Directory.Build.props) to import many code analyzers to all projects.
A custom .ruleset file is also specified [there](https://github.com/t03apt/sonarlint-visualstudio-tests/blob/84471ff5afaa3ecc19bc5d99b99c70c5b6f8e55c/Directory.Build.props#L4).
[Here](https://github.com/t03apt/sonarlint-visualstudio-tests/blob/84471ff5afaa3ecc19bc5d99b99c70c5b6f8e55c/CodingRules.ruleset#L4) I am importing the other .ruleset generated by the SonarLint plugin.

SonarLint VS plugin does not recognize these shared imports.
When I click on Update in 'Test Explorer - Sonar Qube' window, it always creates needles rulesets for each projects. For example: \ClassLibrary1\ClassLibrary1.ruleset.
It also inserts needless PropertyGroups to .csproj files like

```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <CodeAnalysisRuleSet>ClassLibrary1.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <CodeAnalysisRuleSet>ClassLibrary1.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
```

Note: I removed .sonarlint\TestSonarlint.slconfig from the example repository because it has some confidential information.

**Comment by t03apt** [comment]
SonarLint VS plugin also can't update `<PackageReference Include="SonarAnalyzer.CSharp" Version="..." />` defined in Directory.Build.props.

**Comment by duncanp-sonar** [comment]
@t03apt agreed, SLVS doesn't work well if you have manually configured your solution.
SLVS is using VS extensibility interfaces to set the ruleset ([IVSBuildPropertyStorage](https://docs.microsoft.com/en-us/visualstudio/extensibility/saving-data-in-project-files)) and to update the NuGet packages ([IVSPackageInstaller](https://docs.microsoft.com/en-us/nuget/visual-studio-extensibility/nuget-api-in-visual-studio#ivspackageinstaller-interface)). Neither of these interfaces give much control over where the settings are stored (e.g. the _IVSPackageInstaller_ always seems to update the main project file) so there may not be much we can do about updating a _Directory.Build.props_ files instead.

However, we might be able to do a better job of detecting that a project is already configured and so not prompt to update.

Also, as of v4 SonarLint for Visual Studio won't add the NuGet package references to every project, Instead, it relies on the analyzers embedded in the VSIX, so that should be one less problem.

**Comment by duncanp-sonar** [comment]
FYI I've created #790 to track one of the specific issues raised in this ticket. That bug will be fixed in the next version of SLVS.

**Comment by duncanp-sonar** [comment]
FYI I've added a separate issue about adding unconditional ruleset property references: #805
