### ISSUE TITLE
SonarAnalyzer NuGet packages not added in new connected mode (SLVS v4 onwards)

### ISSUE THREAD

**Issue by FooBar08** [SonarSource/sonarlint-visualstudio#695]
### Description

The SonarLint extension should add SonarAnalyzer to enable analysis during build. In earlier versions of the extension the SonarAnalyzer NuGet package(s) were added. Later versions should use the Analyzers that are packaged in the VISX.

### Repro steps

Please provide the steps required to reproduce the problem

1. Bind a solution to a SonarQube project
2. Edit the Visual Studio project to perform code analysis during build
3. Add code that violates a SonarQube rule
4. Build the project
5. Validate that the rule violation isn't raised as build warning

### Expected behavior

Rule violation is reported as build warning.

### Actual behavior

No rule violation is reported as build warning.

### Known workarounds

Add the SonarAnlyzers by installing the SonarAnalyzer NuGet package.

### Related information

* SonarLint for VS Version: 4.1.0.3539
* Visual Studio Version (e.g. Professional v15.4.1) : v15.7.4
* SonarQube server version: 10.1
* Languages in your solution (C#, VB.Net, Javascript, C, C++): C#

**Comment by duncanp-sonar** [comment]
@FooBar08 this change is by design - see #521 and the MMF it refers to.
To summarise, the change was made for a number of reasons which included addressing complaints that automatically adding NuGet packages slows builds needlessly in the IDE since the same issues are already reported in the IDE by the VSIX.

We know that some users will still want to add the NuGet packages directly to the projects, but based on the feedback we've decided not to make that default for connected mode. If you do manually add the NuGet packages, the rules in the NuGet package will be used in preference to those in the VSIX.
