### ISSUE TITLE
SonarLint Output window in Visual Studio

### ISSUE THREAD

**Issue by usmrtester** [SonarSource/sonarlint-visualstudio#713]
I brought up a project in Visual Studio then went to a meeting.  The project was not running in Debug or Release, just idle.  In the VS Output window (for SonarLint), it shows

Initializing the telemetry package...
Finished initializing the telemetry package...
Initializing the notifications package...
Not connected: not checking for notifications
Finished initializing the notifications package
Initializing the daemon package...
Finished initializing the daemon package.
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...
Saving notifcations settings...

Questions:
Can telemetry package be turned off?
Why does it keep "Saving notifcations settings..." (FYI: notifcations is spelled wrong, should be notifications)

* SonarLint for VS Version:  4.3.0.3718
* Visual Studio Version (e.g. Professional v15.4.1)  VS 2017 15.8.1
* SonarQube server version N/A
* Languages in your solution (C#, VB.Net, Javascript, C, C++) C#

**Comment by duncanp-sonar** [comment]
Yes, telemetry can be turned off. Select _Tools_, _Options_, _SonarLint for Visual Studio_ and uncheck the the box on the _General_ tab. The telemetry package will still be loaded but it won't send any data.

Notifications settings: SonarLint implements the VS callback API [IVsSolutionPersistence.SavePackageUserOpts](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivssolutionpersistence.savepackageuseropts?view=visualstudiosdk-2017#Microsoft_VisualStudio_Shell_Interop_IVsSolutionPersistence_SavePackageUserOpts_Microsoft_VisualStudio_Shell_Interop_IVsPersistSolutionOpts_System_String_) to store whether notifications are enabled for the current solution at a per-user level (i.e. in the _.suo_ file that is stored somewhere under the _.vs_ directory for the solution).

VS decides when to call the callback. My guess is that the reason you're seeing it multiple times is because of VS's auto-recover feature - VS periodically saves files in the background so they can be recovered if VS crashes. VS should only all background save on files that have changed, but it's possible it always calls _SavePackageUserOpts_ to be on the safe side since it can't know whether the data being stored has changed or not. You can configure how often VS triggers a background save in _Tools_, _Options_, Environment_, _AutoRecover_.

Thanks for pointing out the typo in the output window message.
