### ISSUE TITLE
Re-authentication required on re-opening an authenticated solution

### ISSUE THREAD

**Issue by StephenLarkin** [SonarSource/sonarlint-visualstudio#765]
### Description

When opening an already authenticated solution, the plugin does not read from an existing authentication token, and instead prompt for a new authentication token each time the solution is opened.

### Repro steps

1. Open a solution.

2. Add SonarCloud plugin and authenticate to a private project.

3. Close the solution

4. Re-open the solution

![sonarcloudpluginauth](https://user-images.githubusercontent.com/3467306/48075795-e0c69c00-e1db-11e8-8b25-197f6daa2690.PNG)

### Expected behavior

User is logged back in and the plugin uses existing authentication

### Actual behavior

User is logged out and prompted to enter new credentials through the gold bar.

### Related information

* SonarLint for VS Version : 4.7

**Comment by valhristov** [comment]
@StephenLarkin I am onto this problem and I cannot reproduce it. I suspect it is related to #772, but I cannot figure out how could you authenticate successfully once and then not. 

Could you try scanning the network traffic to `https://sonarcloud.io` using [Wireshark](https://www.wireshark.org/) or [Fiddler 2](https://www.telerik.com/fiddler) and see if there are redirects in the requests SonarLint is doing to `https://sonarcloud.io`?

**Comment by StephenLarkin** [comment]
Hi @valhristov I have used Fiddler to check, and there are no redirects.

**Comment by valhristov** [comment]
Thanks for the reply! I would really appreciate if you could help me to find the root cause for this problem by doing the following simple test:

1. Open the Windows `Credential Manager` and under `Windows Credentials` find the credential SonarLint created for https://sonarcloud.io - it's name starts with **SonarLint.VisualStudio.Integration** and delete it.
2. Create a new authentication token in https://sonarcloud.io with a user that has access to the private project you are binding to.
3. Open an empty Visual Studio and go to Tools -> Options -> SonarLint for Visual Studio -> General and choose **Verbose** in the SonarLint output verbosity dropdown.
4. Using the new token to authenticate with SonarCloud, do the steps needed to reproduce the problem
5. In the Visual Studio Output window, choose **SonarLint** from the **Show output from** dropdown and look for `Created request of type 'SonarQube.Client.Api.Requests.V6_20.GetProjectsRequest'.`. There could be multiple requests like this and they should all have the same parameters. After this line there is a serialized http request, that looks like this:
```
Method: GET, RequestUri: 'https://sonarcloud.io/api/components/search_projects?organization=sonarsource&asc=true&p=1&ps=500', Version: 1.1, Content: <null>, Headers:
{
  Authorization: Basic BASE64ENCODEDSTRINGHERE=
  User-Agent: SonarLint
  User-Agent: Visual
  User-Agent: Studio/4.7.0.0
}
```
6. Decode the BASE64-encoded string that's in the `Authorization` header - that's the authentication token (I guess you could use any online encoder/decoder to do that) and it should be the same as the one you generated.
7. In the Windows `Credential Manager`, a new SonarLint credential for https://sonarcloud.io should appear and it's user name should be the same as the token (I know, it is silly, we should use the password field for the token) you generated.

Please, let me know the results of the steps.

**Comment by StephenLarkin** [comment]
Sorry for the delay in getting back to you.

It seems that after resetting everything and re-authenticating, the extension now works as expected. I can't be sure what caused the initial behavior, but I'll start seeing if some of my colleagues can enable it, and if we run into the same behavior I'll let you know.

**Comment by valhristov** [comment]
Thanks for getting back to us!
