### ISSUE TITLE
c++ solution cannot connect to sonarqube

### ISSUE THREAD

**Issue by hslxzdz** [SonarSource/sonarlint-visualstudio#769]
**Description**
c++ solution cannot connect to sonarqube

**Repro steps**
Please provide the steps required to reproduce the problem

Install SonarLint for Visual Studio 2015 (V4.7.02556).

**Open a solution**

Browse Analyze-> Manage SonarQube Connections. Connect Link is disabled.

Does our sonarlint for VS not support C++ solution connect to sonarqube? If not ,can I choose sonarqube runner?
![image](https://user-images.githubusercontent.com/17683543/49267096-b3e06e80-f493-11e8-9c94-5c7d8ab34cc1.png)

**Expected behavior**
Connect Link is enabled.

**Actual behavior**
Connect Link is disabled.

**Known workarounds**
N.A

**Related information**
SonarLint for VS Version (4.7.0.3891)
Visual Studio Version (community V4.7.02556)
SonarQube server version 6.7.5.38563
Languages in your solution (C++)

**Comment by duncanp-sonar** [comment]
Connected Mode is not currently supported for C++ (or JavaScript) so the default set of rules will always be used for C++. This issue is tracked by #770.

SonarLint uses an embedded version of the C++ analyser to analyse C/C++: it cannot be configured to use one of the standalone SonarQube Scanners instead.

**Comment by duncanp-sonar** [comment]
I haven't worked on the SonarC analyzer so I can't give a definitive answer, but my guess is that the SonarC analyzer isn't attempting to analyze the code in your second example because it won't compile i.e. it is invalid C++ and can't be parsed correctly.

FYI the best place to ask general questions as at https://community.sonarsource.com/ which is monitored by more people from SonarSource and from the community (only a few people from SonarSource look at issues in this repo, none of whom have worked on the SonarC analyzer).

**Comment by hslxzdz** [comment]
emm, I see, Thank you very much.
