### ISSUE TITLE
Generated ruleset should use the severity specified in the Quality Profile

### ISSUE THREAD

**Issue by duncanp-sonar** [SonarSource/sonarlint-visualstudio#808]
### Description

The severity of rules in the generated ruleset is set to _None_ or _Warning_, regardless of what the value set in the Quality Profile. The severity should be based on the value in Quality Profile (it won't be a 1-1 mapping since the error levels in to

### Repro steps

1. Bind a solution to SonarQube

2. Look at the rule severities in the generated ruleset.

### Expected behavior

The severities are mapped to those in the Quality Profile, and are updated when the Quality Profile changes.

### Actual behavior

The severities are set to _None_ if the rule is disabled or _Warning_ if the rule enabled.

### Known workarounds

None

### Related information

* SonarLint for VS Version: all

### Implementation Notes
The mapping from Sonar to VS severities is as follows:

Info -> Info
Minor -> Info
Major -> Warning
Critical -> Warning
Blocker -> Warning

We've decided to start with to treat `Blocker` as a `Warning` to avoid the risk of breaking local builds. However, as an experimental feature there is an environment variable that will treat `Blocker` as `Error.
Note:
* this experimental feature could be removed without notice at any time.
* to use it, set the `SONAR_INTERNAL_TREAT_BLOCKER_AS_ERROR` to "true"; then restart VS, and update the binding configuration to force the ruleset to be regenerated.

**Comment by BlackAngelTiger** [comment]
@duncanp-sonar Do you have an mapping of SonarQubes severity's and VisualStudios error types?

I would make something like:
SonarQube -> VS Type
Info            -> Info
Minor        -> Info
Major        -> Warning
Critical      -> Warning
Blocker     -> Warning

The problem is that error breaks the build and the static code analysis should not break the local compilation of the solution. For new projects that might be ok, but for older projects not started in development with SonarQube analysis there can be Critical and Blocker issues you will not fix which then prevent the compilation.

I note this because i do not think that you will make the mapping configurable and to use the error type will rase a lot of frustration since i already disused it with a few developers.

**Comment by duncanp-sonar** [comment]
@BlackAngelTiger good point; we wouldn't want to block local builds by default.
There are a couple of additional considerations:
* there might be cases where the user does want Critical/Blocker issues to be treated as errors, although this might be by per-project or -solution. We'd have to think about how/whether to offer this as an option.
* setting the _Severity_ to _Error_ only prevents the local build from completing if the analyzers are installed as NuGet packages. If the error-level issues are caused by analyzers in a VSIX then they appear as errors in the error list but don't prevent local builds (because the VSIX analyzers are not executed in the build). However, if there _are_ an errors in the build for other reasons then the developer would need to use filter the error list to show _Build Only_ issues to see those errors.

**Comment by duncanp-sonar** [comment]
Closing as a duplicate (superceded by #884)

**Comment by dishavirk** [comment]
Hi @duncanp-sonar ,

this issue is still not fixed for C# analysers, I'm using SonarLint for VS2017 and despite innumerous tries, the severity of the custom rules is still being set to _Warning_ regardless of their severity in the Quality Profile on SonarQube.
Since this ticket is closed, I was presuming that the issue is fixed but it seems to be still open. As a part of my troubleshooting, I reinstalled the SonarLint plugin, tried fetching the custom rules for different projects but none worked. It's critical for our projects to have a fix for this as soon as possible.
Can you please advise here?

**Comment by duncanp-sonar** [comment]
Hi @dishavirk. I suggest you try the following:
* check you have the latest version of SLVS installed.
* update your binding in VS e.g.
![image](https://user-images.githubusercontent.com/10757559/87289105-1e70e180-c4f4-11ea-8c27-ff419e165ba8.png)
* ... then check the generated ruleset for C# in the `.sonarlint` folder at solution level. It should contain a mix of `Action` values e.g .`None`, `Warning`, `Information`.

If it doesn't, please open a ticket in the [community forum](https://community.sonarsource.com/c/help/sl/11) with more information, such as a copy the generated ruleset and a screen shot of the Quality Profile.

**Comment by sachin-agarwal-by** [comment]
@duncanp-sonar I’m using SonarLint for VS2019 and facing same issue as @dishavirk mentioned.
I tried all the way but its always showing None or Warning.
Can you please advise ?
SonarLint version : 4.31

**Comment by duncanp-sonar** [comment]
([Duplicate question](https://community.sonarsource.com/t/sonarlint-should-use-the-severity-specified-in-the-quality-profile/38691) in the forum, answered there)

**Comment by lg2de** [comment]
@duncanp-sonar Would you accept a PR which makes the mapping configurable?
For better development workflow we would like to get all (active) rules mapped as warning (again).
