### ISSUE TITLE
SonarLint for Visual Studio 2019 fails to install

### ISSUE THREAD

**Issue by JanSchreuder** [SonarSource/sonarlint-visualstudio#995]
I downloaded the VSIX file for Visual Studio from the Visual Studio Marketplace. The installation failed to completed. I renamed the VSIX to be a zip file and extracted all files. ZIP informed me that Google.Protobuf.dll was corrupt.

How can I fix this? I used SonarLint in VS 2017 before without any issues. I am now using Visual Studio 2019 Enterprise, version 16.2.1.

**Comment by duncanp-sonar** [comment]
@JanSchreuder I've just installed SLVS 14.11.1.0 on VS2019 16.2.1 from the marketplace and it worked fine.

I haven't heard of any problems with marketplace installs before so I'm not sure what to suggest except to try downloading again.

If the VSIX installer failed there should be an error log. Does it give any clues about the cause of the error?

**Comment by JanSchreuder** [comment]
@duncanp-sonar I attached the log file so you can see the error. But I followed your suggestion and downloaded it from the marketplace again. I noticed that this time the was 12,062 KB in size. The one I downloaded yesterday was 3,842 KB in size. Oddly enough I did not see download errors yesterday. 

The new download installed just fine. So I can finally start enjoying Sonar in my new VS 2019.
[dd_VSIXInstaller_20190808071434_242c.log](https://github.com/SonarSource/sonarlint-visualstudio/files/3480046/dd_VSIXInstaller_20190808071434_242c.log)

Thank you for your help

**Comment by duncanp-sonar** [comment]
@JanSchreuder thanks for the update and the log. I guess there was just a glitch during the download.

FYI v4.12 of SLVS was released yesterday evening. It now embeds the C++ analysis rules, which is why the new VSIX is larger than the previous one. There will be a product announcement shortly, but in the meantime the release notes are [here]([v4.12](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v4.12.0.10191)).
